### ISSUE TITLE
collection objects lost respositories

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#1]
Apparently repositories so far unknown to TW did not migrate, and the corresponding types and other collection objects are now with "Repository: not specified". Some examples:

African Natural History Research Trust, Hereford, UK (ANHRT) - 326 in total / 26 types (repo added for new specimens)
Akdeniz University, Department of Biology, Zoological Museum (AUZM) - 50 in total/42 types
Emirates Center for Wildlife Propagation, Morocco (ECWP) - 25/2
Institut National Agronomique de Tunisie (INAT) - 20/0
Universiti Brunei Darussalam Museum (UBDM) - 18/15
Collection B. Massa, University of Palermo (BMPC) - 206/42
C. Hemp Collection - 35 types
Heller Collection - 528/36
Museu Anchieta, Porto Alegre (MAPA) - 1 holotype
Collection of Sheyla Yong, La Habana, Cuba - 28/20
Brazil, Paraná, Curitiba, Universidade Federal do Paraná, Museu de Entomologia Padre Jesus Santiago Moure (DZUP) - 81/22
Insect collection of Agriculture Science Center, Ghyalchok, Gorkha, Nepal - 13/5 (repo added for new specimens)
Annapurna Natural History Museum, Pokhara, Nepal (ANHM) - 6/6 (repo added for new specimens)

I guess we'd need to filter first the types for Repository not specified and then other collection objects to find all cases and think how to solve this.

**Comment by typophyllum** [comment]
I guess these repos are all missing in TW (I added the first one for new types in Massa 2023). So far I counted more than 1200 specimens without repo, almost 200 of them types, and there are probably many more.

**Comment by mjy** [comment]
@typophyllum You can do a lot of queries in filter CO to get numbers. This is "without repository": /tasks/collection_objects/filter?per=50&repository=false&extend[]=dwc_occurrence&extend[]=repository&extend[]=current_repository&extend[]=collecting_event&extend[]=taxon_determinations&extend[]=identifiers&exclude[]=object_labels&page=1. 

So yes, there are many records without Repository linked, maybe 1/3 of the close to 100k.

Note, don't confuse "current repository" (a repository, typically not provided, indicating the current physical location of the specimen, with "repository" (the "home" repository, where it will ultimately reside). 

Another note- "Current repository = with` may be broken.

**Comment by LocoDelAssembly** [comment]
> These repos are probably all missing in TW (I added the first one for new types in Massa 2023). So far I counted more than 1200 specimens without repo, almost 200 of them types, and there are probably many more.

Technically are all missing, but maybe a "synonym" exist for some of them.

**Comment by typophyllum** [comment]
The original OSF has numerous specimen records without repository (unknown or georeferenced field observations linked to photos of live individuals). Would it be possible to match the respos in the old OSF (or all species files) against the ones used in TW, to see which ones are missing? Otherwise we would need to filter for those that are types and don't have a repo (such already exist in the old OSF, but not that many). The lost repos with only normal specimens (e.g. INAT) will be more difficult to find.

**Comment by LocoDelAssembly** [comment]
Notes on how repositories were mapped by Marilyn (and others?):
```sql
/*
Notes about SF depos and mappings onto TW repos:  

        This task was done manually on SFdbMB database (finished 22 June 2017). Max(DepoID) was 3693. Max(DepoID) on SFdb on the same date 
        was 3725. Updates could be manually mapped using the max(DepoID) as a basis, though may not be a useful exercise. Any unmapped depo
        should have a DepoString associated with it which can be used as a data_attribute or note associated with the collection object, etc.
        This program to generate sfDepoStrings should be rerun when a new import with fresh data is processed.
        
        The mapping process started with a spreadsheet containing the TW repo_id, acronyms and name columns (Excel files TWrepos.xlsx,
        TWrepos.xls, and TWreposBACKUP.xlsx). A new column was added as SFDepoIDarray which contained comma separated SFDepoIDs corresponding 
        to the TW repo. The two columns, TWDepoID and SFDepoIDarray (longest record length = 120 characters), were eventually (through a very 
        ugly process) put in tabular form, sfTWDepoMappings.  This is the table that is made available to TW as tab delimited text file. The 
        depo data should be uploaded then generated into a hash consisting of the SFDepoID as key and the TWRepoID as value.
        
        Query to generate sfTWDepoMappings: SELECT * FROM [SFdbMB].[dbo].[sfTWDepoMappings] where TWDepoID > 0 order by TWDepoID
        
        Note: The following depos are now found in grbio.org website that were not in TW (and the corresponding SFDepoID):
                ABCL (2257), HN (3174), UBDH (3715)             
*/
```

**Comment by typophyllum** [comment]
So all depos added or modified after June 2017 couldn't migrate appropriately?

**Comment by LocoDelAssembly** [comment]
Added, I don't think modifications causes depos to be lost given they preserve their DepoID.

**Comment by typophyllum** [comment]
Could you perhaps extract from the old species files a list of DepoID, full depository name, and species file number? So we could verify especially the ones with DepoID > 3693.

**Comment by LocoDelAssembly** [comment]
What information is missing in the spreadsheet linked [here](https://github.com/sfg-taxonpages/orthoptera/issues/1#issuecomment-1714126257)?

**Comment by mabecabrera** [comment]
In this case... OSF seems to have a duplicated repository. 
<img width="611" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/5f6bb0bd-18a5-43ec-9673-5633da5a0c43">

Just informing here to keep track
In TW it is present as 
<img width="930" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/b0d7120d-ed2d-4ab3-bf21-824af5717e7a">

**Comment by typophyllum** [comment]
The 225 specimens in the Shanghai Entomology Museum, Chinese Academy of Sciences (SEM) seem to have been distributed into several different repos, or what happend here?

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/6774f3aa-46c5-4ab8-8f60-0fc7f33ef1aa)

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/d3d4f2b3-3b3c-4623-919e-4c2b687fecb9)

**Comment by LocoDelAssembly** [comment]
I think them were mapped to IEAS

https://sfg.taxonworks.org/tasks/collection_objects/filter?per=50&repository_id=4764&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels&page=1

https://sfg.taxonworks.org/repositories/4764

I guess it is incorrect?

**Comment by typophyllum** [comment]
Yes, Institute of Entomology IEAS has Project use: 229. At least it isn't totally incorrect. It's probably identical to SIES. A new holotype I just assigned to SHIM. Very confusing.

**Comment by LocoDelAssembly** [comment]
[log.txt](https://github.com/sfg-taxonpages/orthoptera/files/12810923/log.txt)
