### ISSUE TITLE
synonyms not accessible

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#10]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/6e1f7d5a-e2ba-40de-b9ad-721fc26757e6)

I cannot access the synonyms. Why is this important? There might be a type specimen and picture associated with the synonym...
In addition synonimisation is always a matter of debate. We therefore need to see all information swiftly associated with synonyms (would be great to see thumbnails!)

**Comment by mjy** [comment]
In TW/TP we have the concept of "coordinate OTUs".  All the panels on a TaxonPage (biological entity, not name) page draw data from all of the biological concepts linked by proxy of the nomenclature.  I.e. if there are images for concepts (Images are linked in many ways, through OTUs, Specimens, Observations etc.), then you should see them on the page in question without having to go elsewhere.  Given this, if you are not seeing images (or map data, etc.) you expect to see let us know.

Side notes. When we model data we think of assertions and inferences.  We have modelled nomenclature assertions seperately from biological circumscriptions assertions in TaxonWorks.  We have modelled it as a historical record, i.e. one that can be transcribed objectively. For example, it is not in question when two _names_ are proposed as synonyms. When we record a name we are modelling it under these assumptions.

Now, whether or not the two biological entities linked to those names are in fact 1, is, as you note,  another question.  In TaxonWorks we have multiple mechanisms for allowing two concepts to reference, for example, the same name, or partially overlap, etc. In practice, however, most curators maintain a 1:1 list of Names to OTUs, though we have the power to abstract away from this incorrect assumption in the data model in TW.

**Comment by klausriede** [comment]
In any case I would like to have a link leading me directly to U. palliata (for example, in this case). Then I can have a look into the synonym citation, synonym type (there has to be a holotype for this name) etc...

**Comment by MMCigliano** [comment]
Yes, there is a holotype for U. palliata and you can find that info in the Nomenclature panel together with the synonym citation. If there were any photos (not this case), those would be shown in the panel for images. 
However, the information that is still missing is connecting the type labels  to the images.

**Comment by MMCigliano** [comment]
the new tab displaying specimen records displays the complete information of the images and type labels

**Comment by klausriede** [comment]
much better, looks good
