### ISSUE TITLE
Subgenus Homeomastax?

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#103]
Under Homeomastax (gen), you have the subgenus Homeomastax with only H. surda as a species. But you also have H. surda as a superspecies under Homeomastax (gen), but with no H. surda under that superspecies. 

I think, if I understand correctly, that H. surda (sensu stricto) should be under the superspecies of the same name, and get rid of Homeomastax (subgen), since the presence of a subgenera would incite the idea that multiple subgenera are present (which it's not).

https://orthoptera.speciesfile.org/otus/826674/overview

**Comment by MMCigliano** [comment]
Thank you @SeanCozart, you are right.
Correction made.

**Comment by klausriede** [comment]
MAYBE REFERRRING  to species group http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1217233 Species group Homeomastax (surda) (Burr, 1899)? in any case, a species group is not a superspecies????

**Comment by MMCigliano** [comment]
@klausriede Names proposed for an aggregate of species denoted as "Species groups" in Species file Software are called "superspecies" in TW, following recommendations of ICZN (see art. 10.4)

**Comment by klausriede** [comment]
thanks!!!
