### ISSUE TITLE
New publication resurrects synonym as a species

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#104]
A new publication brings Tachycines coreanus out of synonymy with Tachycines asynamorus, after it was synonymized in 2018. The former species was (inappropriately) added back into iNaturalist, and has caused to some arguments over whether or not we deter from OSF or continue following the taxonomic source. Due to how recent the newest publication, I said I would drop this request, since it's almost certainly a case of being unaware of the new information rather than a deliberate attempt to be an outdated database. 

https://www.nature.com/articles/s42003-024-06068-x

**Comment by MMCigliano** [comment]
@SeanCozart , thank you. 
We have removed the name from synonymy
