### ISSUE TITLE
Ommatolampis not linked properly? 

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#105]
On the genera page, Ommatolampis is linked directly to Acrididae. But on the Acrididae page, it is not listed as a descendant taxon. I think it should be attached to Ommatolampina due to name similarity and the likelihood that the subtribe was named after the type genus.

https://orthoptera.speciesfile.org/otus/822321/overview -- Ommatolampis page
https://orthoptera.speciesfile.org/otus/809570/overview -- Acrididae page
https://orthoptera.speciesfile.org/otus/822316/overview -- Ommatolampina page

**Comment by klausriede** [comment]
Yes, indeed, as correctly layed out in OSF5.0 http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1222803
Another migration error?

**Comment by typophyllum** [comment]
Thank you. The correct subtribe name seems to be Ommatolampidina (not in the old OSF but apparently created by the migration). I will look at this.

**Comment by MMCigliano** [comment]
@SeanCozart, thank you. 
Correction made.
