### ISSUE TITLE
Leticiacris amazonica

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#106]
type pic available via gbif https://www.gbif.org/tools/zoom/simple.html?src=//api.gbif.org/v1/image/cache/occurrence/2566056430/media/35b991594da761db62788b13c9676e5b - as said, gbif tab might be more informative than inaturalist or Xenocanto (notabene: this group does NOT produce any song), because it would generate pics of both collection items as of observations of any citizen site connected to gbif...

**Comment by typophyllum** [comment]
This is the species page on GBIF:
https://www.gbif.org/species/1710715

The type is with the second occurrence dataset:
![imagen](https://github.com/user-attachments/assets/4eac52ca-d103-45ee-b3c0-d2eb822b5079)

**Comment by typophyllum** [comment]
The question of website design, the currently rather limited usefulness of the iNat and xeno-canto tabs, as well as additional possible tabs, should probably be discussed elsewhere and under a more informative title.

**Comment by klausriede** [comment]
@mjy @debpaul @MMCigliano definitely agreed, particularly because I am a user and not a designer...#userneeds
