### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#109]
I suppose "synonym" Prozvenella bangaloriensis is a mis-spelling hidden in one of the "nomenclatural" references? Would be good to clarify this by a respective disclaimee [misspelling], [m] etc https://orthoptera.speciesfile.org/otus/835143/overview

**Comment by typophyllum** [comment]
Thank you. This wasn't yet appropriately specified.

![imagen](https://github.com/user-attachments/assets/56c8969e-e2e5-48b6-a28a-d2b62a880fd2)
