### ISSUE TITLE
museum data not congruent

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#11]
http://orthoptera.speciesfile.org/Common/basic/ShowImage.aspx?TaxonNameID=1104036&ImageID=155242

cf old and new version....Image source not visible in new version (DORSA Ingrisch...)

**Comment by LocoDelAssembly** [comment]
https://sfg-taxonpages.github.io/orthoptera/#/otus/810676/overview
![image](https://github.com/sfg-taxonpages/orthoptera/assets/4991925/4251f1e7-a235-455c-b264-5e227afa225e)
