### ISSUE TITLE
Stenobothrus vagans https://orthoptera.speciesfile.org/otus/812641/overview

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#111]
...seems Pantel means Chorthippus vagans when he mentions St. vagans? https://bibdigital.rjb.csic.es/medias/25/8f/96/cc/258f96cc-7912-4952-9edd-25e5da67cd0f/files/P0011_15.pdf

**Comment by typophyllum** [comment]
Yes, from 1859 to1926 most authors used this combination. And the species has so many citations in OSF that not all references that simply mention it are cited. Which of Pantel't work is that?

**Comment by klausriede** [comment]
the one linked here: 1886 https://bibdigital.rjb.csic.es/medias/25/8f/96/cc/258f96cc-7912-4952-9edd-25e5da67cd0f/files/P0011_15.pdf

**Comment by typophyllum** [comment]
The link is for a PDF that would take between 20 min. to over an hour to download. in OSF Pantel 1886 has a link to access the corresponding page within less than a minute.

**Comment by klausriede** [comment]
sorry, all this works quick in Europe. In fact I got the link from OSF but only saw the respective page,
