### ISSUE TITLE
Odaleus nigrofasciatus asserted distr in Spain

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#112]
...seems Pantel p 273 https://bibdigital.rjb.csic.es/medias/25/8f/96/cc/258f96cc-7912-4952-9edd-25e5da67cd0f/files/P0011_15.pdf means https://orthoptera.speciesfile.org/otus/809873/overview speaking about Pachytylus nigrofasciatus. would be good to add his list because it is from ONE site in Spain 19th century

**Comment by typophyllum** [comment]
Seems to be from the Cape Peninsula in South Africa. Could the old records from Europe refer to misidentifications?

**Comment by klausriede** [comment]
the question is the use of this name at that time....#timeline

**Comment by typophyllum** [comment]
According to Ritchie 1981 (A taxonomic revision of the genus _Oedaleus_ Fieber) _Odaleus nigrofasciatus_ was partly confused with _Oe. decorus_ by old authors, namely Schaum 1853, Stål 1873 and Kirby 1910, and he cites no references with European records. All his examined specimens come from South Africa, Namibia, Botswana and Zimbabwe. "Widely ditributed and common through southern Africa south of the _Brachytsegia_ woodland. Specimens labelled as _Oedaleus nigrofaciatus_ var. _gracilis_ from Russia in the MHN Geneva are actually also _Oe. decorus_.

**Comment by typophyllum** [comment]
For grasshoppers a more recent source would be Presa, García &  Clemente 2007, Catalogue of Orthoptera Caelifera from the Iberian Peninsula and Balearic Islands (Orthoptera: Caelifera), Journal of Orthoptera Research.16(2):175-179 ... I think we added asserted distributions from that paper.

For which species occurring in Spain are actually missing corresponding data?
