### ISSUE TITLE
subjective synonym 

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#113]
I do not understand "Euchorthippus pulvinatus gallicus Maran, 1957 (subjective synonym of Euchorthippus elegantulus Zeuner, 1940) in Defaut, 2014: 9. " How does this justify a Tp page differing from the original description? https://orthoptera.speciesfile.org/otus/813185/overview

**Comment by typophyllum** [comment]
I'm not sure what the question is. Numerous authors treat this a valid subspecies, including Orci, Ragge & Reynolds 2002 (A re-examination of the taxonomy of Euchorthippus pulvinatus and related species on the basis of morphology and song):
![imagen](https://github.com/user-attachments/assets/47f3c877-679c-4720-b23c-863d42e97e7a)

Only Defaut thinks it's a synonym, but cites only Ragge & Reynolds 1984:
![imagen](https://github.com/user-attachments/assets/05c3aba3-44d1-4848-9c6f-996aad69a417)
![imagen](https://github.com/user-attachments/assets/040e624d-0dfa-4f72-bb10-6a9c82e3ada9)

**Comment by klausriede** [comment]
that s confusing https://orthoptera.speciesfile.org/otus/813185/overview cites correctly the original susp descrition E pulvinatus gallicus Maran, how can this be moved to E elegantulus? I will try to undertand the respective literature. In any case, and as always, depictions of oscillograms woould be helpful

**Comment by typophyllum** [comment]
In the Orci et al. paper they explain it. _Euchorthippus pulvinatus_ has a more eastern distribution.

**Comment by typophyllum** [comment]
Figure from Orci et al. 2002:

![imagen](https://github.com/user-attachments/assets/884ee62e-1434-40c4-9854-0a4b7fb04c2e)

**Comment by klausriede** [comment]
Thanks! Would really be good to have these pics in the database, I will try to understand the respective publications. As said, Ragge 1998 has E.p. gallicus which would coorespond to elegantulus gallicus in the diagram.

**Comment by klausriede** [comment]
Vielen Dank, Danke! Diese Infos sollten irgendwie in der datenbank sichtbar werden, zB könnte man die Karten als GIS shapes in den Viewer integrieren.....Gruss Klaus


Klaus Riede Global REgister of Migratory Species www.groms.de<http://www.groms.de>


________________________________
