### ISSUE TITLE
BHUPM at https://orthoptera.speciesfile.org/otus/849346/overview

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#114]
![grafik](https://github.com/user-attachments/assets/d8cfbe2c-c436-4741-9ebf-4d5e750552f2)
seems there is a HTML glitch in the pic description, what is BHUPM? See depiction in pic

**Comment by typophyllum** [comment]
BHUMP is an incorrect Namespace for the MfN used for the DORSA-Codes. I corrected it for the three syntypes of this species.

Filtering Collection Objects with Identifier DORSA finds altogether 54. This will be easy to fix. Thought there were more.

**Comment by typophyllum** [comment]
Found a few more COs with wrong Namespace BHUPM, a few more in fact DORSA and a few CH (Collection Heller). Now there remain 23 to be fixed.
