### ISSUE TITLE
more sound recordings here https://sonotheque.mnhn.fr/sounds/mnhn/so/2022-842

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#118]
...unfortunately with a different name for Chorthippus jacobsi

**Comment by typophyllum** [comment]
From the same author Stanislas Wroza are five more recent recordings of _C. jacobsi_ on xeno-canto.

**Comment by typophyllum** [comment]
Not a problem with OSF data. No convincing case to add additional links to sonotheque.mnhn.fr and how those could be generated and updated. Apparently redundant in relation to xeno-canto anyway.
