### ISSUE TITLE
Problem of taxonomy

### ISSUE THREAD

**Issue by JBarataud** [sfg-taxonpages/orthoptera#120]
I am surprised that the genus Eugryllodes appears in subfamily Gryllomorphinae Saussure, 1877 and tribe Gryllomorphini Saussure, 1877.
I thought this genus was more in  subfamily Gryllinae Laicharting, 1781 and tribe Eugryllodini Gorochov, 1990.
Isn't there a mistake?
Thankks
Julien Barataud

**Comment by typophyllum** [comment]
Thank you for the note. In Otte's 1994 catalog _Eugryllodes_ is in Gryllomorphini. Defaut 2001 (Actualisation taxonomique et nomenclaturale du "Synopsis des orthoptères de France") has it indeed in Gryllinae, which would make more sense, since it seems to be related to _Gryllodes_. Eugryllodini is missing on OSF as well as in Zoological Record. Do you have this Gorochov 1990 reference?

**Comment by JBarataud** [comment]
Dear Holger,
I'm sorry, I think I've made a mistake too!
In the reference list of Orthoptera of France (
https://ascete.org/wp-content/uploads/2021/11/5.-Liste-des-Orthopteres-de-France-2021-11-21_ok.pdf),
Eugryllodes pipiens is indicated as belonging to the tribe Eugryllodini
Gorochov, 1990. But after some research, I believe that this tribe does not
exist, as I have found no other reference... And perhaps it's a case of
confusion with the tribe Eurygryllodini Gorochov, 1990 (
http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1123921
).
On the other hand, Eugryllodes pipiens is classified in the Gryllini tribe
by various European reference works such as Harz (1969) or Gorochov &
Llorente (2001). I don't know where this classification in the
Gryllomorphini in Otte's catalogue comes from, but it would seem more
logical to me that this genus should be attached to the Gryllini (a tribe
in which the genus Gryllodes is also found).
Thanks for this quick reply and for all the fantastic work you do on OSF!
Best wishes
Julien Barataud

Le mar. 12 nov. 2024 à 19:30, Holger Braun ***@***.***> a
écrit :

**Comment by typophyllum** [comment]
Dear Julien, I moved _Eugryllodes_ under Gryllini and added a citation to Gorochov & Ünal 2012 (Review of Turkish crickets from the subfamily Gryllomorphinae). In that paper they say explicitly:
"Eugryllodes is a representative of the tribe Gryllini from the subfamily Gryllinae"

Thank you very much!

**Comment by klausriede** [comment]
so we have a supersubfamily Gryllinae and a subfamily Gryllinae?

**Comment by klausriede** [comment]
https://orthoptera.speciesfile.org/otus/828881/overview

**Comment by typophyllum** [comment]
Subfamily group in old OSF, established in Gorochov 2015.
