### ISSUE TITLE
Availability of the genus name Mendesius Piza, 1960

### ISSUE THREAD

**Issue by Laverock2024** [sfg-taxonpages/orthoptera#121]
This name appears to be preoccupied, by _Mendesius_ Roewer, 1943 (Opiliones). It seems strange, given the efforts of various authors to resolve homonyms, that this has never been noticed before; so I would ask whether you have any knowledge of this issue being raised in the past and discounted?  The Roewer name looks to be properly published, with a description, and a type species by monotypy.

Reference: Roewer, C.F. 1943. Über Gonyleptiden. Weitere Weberknechte (Arachn., Opil.) XI. Senckenbergiana 26(1–3): 12–68. 
[https://web.archive.org/web/20240722001607/https://mndi.museunacional.ufrj.br/aracnologia/pdfliteratura/Roewer/Roewer%201943%20Senck%2026%20Uber%20Gonyleptiden.pdf]

**Comment by typophyllum** [comment]
Thank you for bringing this up and the link to the Roewer paper. His name indeed has priority, although it seems to be a synonym of _Gonyleptes_ Kirby, 1819. This went unnoticed so far. I had moved _Hyperphrona signata_ Rehn 1907 to _Mendesius_ Piza in an old manuscript that I should finally finish. It could also be included in another manuscript with miscellaneous nomenclatural notes I am working on, unless you want to propose a subsitute name yourself.
