### ISSUE TITLE
incorrect repository (Museum für Naturkunde: BHUPM instead of MfN)

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#13]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/1e1bc0c3-80db-4027-845d-d380143d8863)

vs

![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/f6d02541-895a-428e-959f-fa7534d095ad)
 
MfN according to http://orthoptera.speciesfile.org/Common/specimen/ShowSpecimen.aspx?SpecimenID=42654

**Comment by typophyllum** [comment]
This is indeed incorrect, BHUPM is the Herbarium Code of the MfN.

**Comment by klausriede** [comment]
Note that there are more incorrect ones see O humilicrus plus there is a DORSA pic for this species, albeit missing in old OSF too https://www.europeana.eu/de/item/11622/ORTHOPTERAXDORSAXMFNXGERMANYXZMBXORTHXBAORTHUMS01

**Comment by LocoDelAssembly** [comment]
Yes, we can do that.

**Comment by klausriede** [comment]
Why is there a herbarium in the OSF list of depositaries?

**Comment by LocoDelAssembly** [comment]
@klausriede Repositories are shared across all projects inside a TW instance (there is no project_id attribute). https://docs.taxonworks.org/develop/Data/tables.html#repositories

**Comment by klausriede** [comment]
suggestion: inlcude a project_id attribute and run some commonsense checkup queries

**Comment by LocoDelAssembly** [comment]
> suggestion: inlcude a project_id attribute and run some commonsense checkup queries

In repositories table? Why?

**Comment by klausriede** [comment]
to avoid that herbaria acronyms appear in zoology speciesfiles...

**Comment by LocoDelAssembly** [comment]
Repositories table is supposed to be a registry of collection institutions like https://www.gbif.org/grscicoll, and it is not meant to be project-specific. Correct action is to move all BHUPM specimens to MfN and not use incorrect repository on future data entry.

**Comment by LocoDelAssembly** [comment]
BHUPM changed to MfN for all COs in OSF.

**Comment by typophyllum** [comment]
Thanks. I just replaced u by ü at Museum für Naturkunde.
