### ISSUE TITLE
Eurypalpae - invalid infratribes

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#15]
not necessarily a software question...:
Eurypalpae mentioned in the 2020 paper: Why is there an X (not valid)?

**Comment by typophyllum** [comment]
Perhaps someone needs to convert this into tribe Eurypalpini, or maybe rather Eurypalpina (genus groups migrated as infratribes to TW). However, ICZN Article 29.2. (Suffixes for family-group names says):

"The suffixes of names for taxa at other ranks in the family-group are not regulated."

**Comment by typophyllum** [comment]
Filter nomenclature for Family group and only invalid at the moment still finds ten infratribes.
