### ISSUE TITLE
Aclodes vittatum

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#16]
...missing

**Comment by LocoDelAssembly** [comment]
https://sfg-taxonpages.github.io/orthoptera/#/otus/832345/overview

**Comment by klausriede** [comment]
Great! But I think still missing in the autocomplete dropdown list when I type Aclodes
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/b7a9be2b-b103-4e2f-b91c-46bd5cfc3fb0)

**Comment by typophyllum** [comment]
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/3f7fa94f-8c6b-426b-a21c-f7881549d40b)

**Comment by mjy** [comment]
Try capitals.

M

**Comment by klausriede** [comment]
Negative. Even when scrolling down
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/efa71a1a-59bd-4af8-bee5-b1ea4ce1517b)

**Comment by typophyllum** [comment]
But already with the first letter of the species name you find it.

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/a0925454-c290-40cd-a803-de80b984b566)

**Comment by klausriede** [comment]
correct. I am used to find a list of all species under Aclodes - maybe I do not know that there is a species vittatum...

**Comment by mjy** [comment]
Autocomplete is search, not browse, you should have a target in mind to use it.  Browse works by clicking through the breadcrumbs or ancestors once on a page.

**Comment by klausriede** [comment]
Yes, I found out already. However if search for Aclodes results in nearly all species for the genus, why is vitt. missing? Anyway, is the autocomplete already modified? I understood that this section willbe modified?
