### ISSUE TITLE
Depository of A. furcifer distinct

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#17]
http://orthoptera.speciesfile.org/Common/specimen/ShowSpecimen.aspx?Router=NewPage

according to OSFold SDEI....

**Comment by typophyllum** [comment]
Are your referring to _Acrotylus furcifer_? Links without TaxonNameID in the URL lead nowhere. The syntype in the old OSF is in the MHNG.  The types of the synonym _Acrotylus aurantius_ are in the BMNH (holotype) and the SDEI (paratypes). The new version is currenty useless to see and compare specimens.

**Comment by klausriede** [comment]
I think the new public version should allow to compare specimens
