### ISSUE TITLE
missing paratypes

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#18]
there are paratypes (with pics!) of ageneotettix salutator in old OSF http://orthoptera.speciesfile.org/Common/specimen/ShowSpecimen.aspx?Router=NewPage missing in the new version

**Comment by typophyllum** [comment]
Currently only the holotype, lectotype, or one syntype are listed for each species (or subspecies) in TaxonPages. All specimens will be shown in a separate tab that needs to be developed. For comparison of specimens based on associated photos the users still need to resort to the old OSF.

**Comment by mabecabrera** [comment]
The pictures are all included in the Public View. 22 pics in old OSF.
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/876d59e6-f8e1-48e0-8971-3eab4b71eca9)

And the new public view also has this 22 pics. When placing the mouse over the image we can see the caption of the picture.
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/37684d5e-597d-49ba-bfca-c5aa44135421)

Also if we click on the three lines menu by the Type specimen section we can see the JSON data...
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/169b865f-7ffc-4ba4-81e2-f9907b1504e8)

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/bfc1a572-0b9c-489e-a9f0-08751c0445a8)

Until we have the new public view as complete as we want to, some things will work better from the TW software.

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/8be03f89-957d-44e1-9040-a8f7785192a4)

**Comment by LocoDelAssembly** [comment]
Related: https://github.com/sfg-taxonpages/orthoptera/issues/19

**Comment by mabecabrera** [comment]
> missing paratypes Amblytropidia trinitatis : in the old version there are paratypes from Panama in SDEI collection (with depictions!) missing in the new version. The collection object from Panama is from another depository

Which is the correct depository? I also find the same infomation in Species Files and Taxon Works.
