### ISSUE TITLE
missing paratypes Amblytropidia trinitatis from the map in Public view

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#19]
missing paratypes Amblytropidia trinitatis : in the old version there are paratypes from Panama in SDEI collection (with depictions!) missing in the new version. The collection object from Panama is from another depository

**Comment by LocoDelAssembly** [comment]
@typophyllum please confirm but I believe data is there when seen from the workbench? Also when using the DwC download feature in public pages you also get the type specimens.

**Comment by LocoDelAssembly** [comment]
@typophyllum please confirm but I believe data is there when seen from the workbench? Also when using the DwC download feature in public pages you also get the type specimens.

**Comment by typophyllum** [comment]
Klaus, as I understand, this GitHub section is for migration errors (wrong or missing data in TaxonWorks), not the limited access to the data on TaxonPages.

There are all the types ot the species and its synonym:
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/ec1869a7-9002-434c-a3e6-e2024e3fd376)

**Comment by mabecabrera** [comment]
Thank you so much @klausriede for all this examples. It helps us a lot to improve and check and correct things. 
I would also add to @typophyllum comment above that it would be more efficient if we use just one issue for each problem. "Missing paratypes" all in the same issue number to follow the case better.

Could we link this one to the #18 @LocoDelAssembly ? So we can keep the track in the same place?

**Comment by LocoDelAssembly** [comment]
Discussion continues at https://github.com/sfg-taxonpages/orthoptera/issues/18

**Comment by klausriede** [comment]
not sure if it helps to follow each small case, I think the number of cases (took me 10 minutes to find them) points to a major problem with migration routines! As said it is fundamental to have some check routines. For example, you could find the number of species for a depositary in old OSF (whihc is a standard complex query) and compare it with the results of the same query (unified filter) in the new version. REsults should be the same. And many more finger exercises you could try...Might be good for teaching purposes

**Comment by klausriede** [comment]
@typophyllum aha, but where do we submit errors in taxonpages? I would strongly suggest that ALL available type information appears in the TP map, so this means that the Gatun lake specimen from SDEI is missing in the TP page

**Comment by mabecabrera** [comment]
Yes! The idea is to find the major problem! 
I think we have errors of the migration that will be also seen from the TP view. We are looking for those and correcting them as fast as we can. And then in TP we have information that is not wrong but is not shown in the best way. That is what is going to be developed in time New Tabs so we can see the info with more detail.

This is the file that is downloaded from the public page... above the map. The DwC button. Those are the complete list of specimens.
<img width="1386" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/2395f148-845a-4c20-ad8a-150068b31b40">

Any idea @jlpereira why they are not showing up in the map? I also tried all the dots and areas represented there and did not find them.

**Comment by mabecabrera** [comment]
It is a case of overlapping of more than one specimen in the same locality in the map. It will be soon solved. José can make it to show like this.

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/1fd2b8c4-7399-4b36-98df-f536698be374)
 
 Thank you Klaus very much for pointing it out!

**Comment by mabecabrera** [comment]
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/6d1983eb-4a2b-4157-8a30-4c51236ce937)

**Comment by klausriede** [comment]
looks much better

**Comment by mabecabrera** [comment]
Yes! Thank you @klausriede and @jlpereira
