### ISSUE TITLE
sources lost names of serials

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#2]
For example:

**Boletín de la Sociedad Zoológica del Uruguay** (three sources, fixed)
**PLoS One** (PLOS ONE in original OSF, 43 sources, a few of them fixed)
**Revista Mexicana de Biodiversidad** (4 sources - fixed)

Is it possible to filter for sources without serial name (but volume and sometimes issue numbers) to find all cases?

**Comment by typophyllum** [comment]
All PLOS One cases fixed.

Tried to change the obsolete spelling PLoS One to PLOS One, but apparenly doesn't work.

**Comment by typophyllum** [comment]
**European Journal of Taxonomy** (ten sources in OSF, fixed)

**Comment by typophyllum** [comment]
**Memoirs of the Entomological Society of Canada** (1, fixed).

**Comment by typophyllum** [comment]
**Proceedings of the Zoological Institute of the Russian Academy of Sciences** (31, so far only Gorochov 2016 fixed)

**Comment by typophyllum** [comment]
**PeerJ** (8)

**Comment by typophyllum** [comment]
**Entomologie heute** (3, fixed)

**Comment by LocoDelAssembly** [comment]
[List of refs potentially missing TW serials](https://docs.google.com/spreadsheets/d/1O0x8-l4s6P1y_Xvn23M895AvcYk3HB8H_8KnZehweLw/edit?usp=sharing)

**Comment by LocoDelAssembly** [comment]
In https://sfg.taxonworks.org/data_attributes you may search by RefID. The search pattern is `SF.RefID <ID>` (e.g. `SF.RefID 8409`)

Although probably I could write some script to have links in TW sources, but in the meantime searching by data attribute should work.

**Comment by mjy** [comment]
@jlpereira and I can make a batch-updater, maybe, to update the Serial of all found records.  Would this help given the search capabilities above^

**Comment by mabecabrera** [comment]
I do not know if I am understanding well. But if we could use the PubID number that @LocoDelAssembly got us in the list he made for us in excel... we could get in one step to all of the souces that belong to the same serial and add that information. 
So we don´t have to add it one by one as we are doing right now.

**Comment by mabecabrera** [comment]
> In https://sfg.taxonworks.org/data_attributes you may search by RefID. The search pattern is `SF.RefID <ID>` (e.g. `SF.RefID 8409`)
> 
> Although probably I could write some script to have links in TW sources, but in the meantime searching by data attribute should work.

Can not follow that. Do not find it or know where...

Also in the filter. I can´t find anything that could help.
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/b907b238-4361-45a8-8ec0-67770543e59c)

**Comment by mabecabrera** [comment]
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/e81110c6-6f44-4571-8a03-48d9df21945b)

The problem is not to find the source becouse we can find it in Species Files or google. The super power would be to get to all the sources with this PubID number. And add it to them all.

**Comment by mjy** [comment]
Side-ish note. I think Source filter is missing data attribute facet like in other filters.  Seeing about adding it now.

**Comment by mjy** [comment]
Source filter data-attribute facet is coming, this might help you.

**Comment by mjy** [comment]
Actually it looks like there are like no DataAttributes added to Sources for Orthoptera... but the facet is coming regardles.s

**Comment by LocoDelAssembly** [comment]
> ![image](https://user-images.githubusercontent.com/63611746/267129153-e81110c6-6f44-4571-8a03-48d9df21945b.png)
> 
> We have 9 sources that correspond to this serial but it only finds one that is complete...

**Comment by mjy** [comment]
Aha.  Not Internal.  So they aren't referenced on the facets  I think?

**Comment by mabecabrera** [comment]
I am trying but I´m no getting to any result.

For instance, I select de Import Attribute SF.RefID and for value add 22780

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/5e3ef9af-0440-48b6-a97b-0d1df97f0e60)

Acording to the excel @LocoDelAssembly created there are 5 souces at least with that serial...

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/0cfc31df-72f5-44dc-a165-a46a6078f4e9)

But it shows only one result of a source out of our project.
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/7787e857-190e-4b9b-8ef0-93a8e15d4538)

Could it be that the problem is that they are not associated yet? I tried with the ones we have already completed...

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/07978687-96af-4df0-a58d-64d1ee2a8055)
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/e613100f-fd55-4ca6-b81f-a414b3a2c6b4)

But non of them is showing up in the filter as I get cero results... Am I using this filter as it is supposed to?

**Comment by mabecabrera** [comment]
Sorry, I did the example using the PubID but have just used the correct one and I do not get any results either.

**Comment by typophyllum** [comment]
This is practically done. Filter sources now finds 17 articles without serial which need further investigation.

**Comment by mabecabrera** [comment]
The Import attribute filter is working! When using the exact/any checkbox! If not clicked it does not find anything! Now we can solve all the cases!!! Thanks!!!

**Comment by mjy** [comment]
> When using the exact/any checkbox! If not clicked it does not find anything! 

Screenshot with difference please?

**Comment by mabecabrera** [comment]
Here I do not  check the exact/any, and do not get results.
<img width="1284" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/5aace091-6dad-45a3-bab2-9624e146fb87">

And here I do check
<img width="428" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/bf462233-5297-44c4-9575-fd81e2e52290">

And I get results...
<img width="1256" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/1f3f9031-1ebe-45ab-8fb3-69188e4fb1d3">
