### ISSUE TITLE
Namespaces (SF IMPORT DUPLICATE) cases

### ISSUE THREAD

**Issue by mabecabrera** [sfg-taxonpages/orthoptera#21]
As some of the Namespaces where already in Taxon Works from another projects, when the migration occured those that matched with the ones in TW where marked with a (SF IMPORT DUPLICATE) legend.

These are just 29 cases and can be filtered by this legend also part of the name.

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/c9a6e040-afff-40a6-b505-5b45c685255f)

So the task will be to go to each one and check if it is correct to merge it with the one that is previously in TW.

After confiming that, @LocoDelAssembly could merge them all with a script.

**Comment by LocoDelAssembly** [comment]
The list of duplicates can be seen [here](https://docs.google.com/spreadsheets/d/19_XNHD8ZoJmM7Y8IIqyAjHVZl13aFhHrqr2eBwNX1AI/edit?usp=sharing).

There is an extra column to paste the URL of the existing valid namespace to use as substitution. When filling that out, it must be carefully checked that the substitution truly represents the original imported namespace, just checking acronym isn't enough.

**Comment by LocoDelAssembly** [comment]
For OSU fix is discussed in https://github.com/sfg-taxonpages/orthoptera/issues/26

**Comment by mabecabrera** [comment]
What do we do when the short name is the same as one already in TW, but is a different collection and institution?

Examples  (the correct in OSF)
UAIC (Centre ORSTOM, Abidjan, Côte d'Ivoire) ... but in OSF there is no short name associated.
OSU (K. C. Emerson Museum, Oklahoma State University)
US (Entomological Collection, University of Stellenbosch, South Africa)

**Comment by mjy** [comment]
Create a second namespace.  The Short name has to be different (it is used to select from a list), the verbatim name is duplicate.

Single repositories can have many namespaces.  Namespaces are not the same thing as repositories, though their short names often overlap, and some consider them 1:1 (we do not).

**Comment by typophyllum** [comment]
I'm frequently coming across species that have (SF IMPORT DUPLICATE) with the type data. Doesn't look very professional. Could this perhaps finally be fixed?
