### ISSUE TITLE
map much better but again no pics

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#25]
http://orthoptera.speciesfile.org/Common/specimen/ShowSpecimen.aspx?SpecimenID=146802 has pics missing in TP for Phaulacridium vittatum. Map much better!
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/e0ab9edb-0a57-4c70-abf1-f930679a0a12)

**Comment by mjy** [comment]
What does this mean?

**Comment by typophyllum** [comment]
Same as #22.

**Comment by klausriede** [comment]
How do I know as a user? I think I found this in the dropdown list and clicked on it!
