### ISSUE TITLE
Results with [c] in the search of public view is confusing

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#27]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/89e28501-775e-4b55-9a88-7ee2587e38ea)

dropdown list for vittatum looks confusing what does (c) mean?

**Comment by typophyllum** [comment]
It stands for (subsequent) combination (original is _Biformalia vittata_, not _B. vittatum_). I think these shouldn't show up in the search box.

**Comment by mabecabrera** [comment]
<img width="627" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/9e3c4580-df2a-41d5-88b7-f2f3aec674d1">
This is in the Help manual for filters and for adding images and specimens. 

I agree that in the public view there is no need to include the OTUs for combinations. I think that if we click on that it redirects to the one with the checkmark. Is it right @jlpereira ?

**Comment by mabecabrera** [comment]
@typophyllum also having two of them is even more confusing. We should check on that. Maybe there is a duplicated OTU.

**Comment by klausriede** [comment]
agreed, confusing! In addition we might need a docu for TPs (or maybe already available?)

**Comment by jlpereira** [comment]
> <img alt="image" width="627" src="https://user-images.githubusercontent.com/63611746/269687322-9e3c4580-df2a-41d5-88b7-f2f3aec674d1.png">
> This is in the Help manual for filters and for adding images and specimens.
> 
> I agree that in the public view there is no need to include the OTUs for combinations. I think that if we click on that it redirects to the one with the checkmark. Is it right @jlpereira ?

Yes, combination/invalid names are redirected to valid names
