### ISSUE TITLE
paratype or allotype?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#29]
https://sfg-taxonpages.github.io/orthoptera/#/otus/807221/overview

It is difficult to relate the pictures to map points. In old OSF there is a holotype and allotype, http://orthoptera.speciesfile.org/Common/specimen/SpecimensByTaxon.aspx?TaxonNameID=1101062 with a set of pictures from berlin and Dresden [Berlin Museum Acronym still wrong!!!!). In Taxonpages allotype is a paratype. Information revealed when hovering over pictures not very informative, would be good to see collection data, instead

**Comment by mjy** [comment]
As a note we do not record "Allotype" in the class of data TypeMaterial as it, nor many many other classes of types are not governed.  Projects will independantly need to add data attributes or tags, for example, if they wish to record such information.  @LocoDelAssembly or @proceps might comment on what we did with that data in the migration.

**Comment by proceps** [comment]
I guess all allotypes were converted to paratypes, although it could be incorrect. ICZN does not cover the term usage. So allotype could be part of the type series, or could be a non type specimen of an opposite sex. A data attribute is probably the best solution. I checked the paratype record for the indicated species, and it does has a data attribyte indicating that this is an allotype. The specimens have associated depipctions, but the label could probably be update. The repository may need to be updated. You can use Collection Object filter to search for a particular repository, after that, I am not sure if you can update all collection objects with new repository, or the records need to be updated one by one. Unfortunatelly all repositories are identified by their abbreviations, and there could be some discrepencies between OSF and TW.

**Comment by klausriede** [comment]
Not sure what others think but personally I would strongly suggest to use the type classification used in the source. Any conversions of terminology, names endings etc by TW should be highlighted!

**Comment by typophyllum** [comment]
Since allotypes aren't regulated by the Code (Recommendation 72A: no name-bearing function) they probably should have been left alone. According to the Code they aren't paratypes. And among real paratypes with identical collection data they are now difficult to recognize.

**Comment by klausriede** [comment]
As a general lesson I would strongly suggest to leave data as they are provided or found in the literature. Any changes due to import or interpretation from taxonworks software should be highlighted. e.f.q.
