### ISSUE TITLE
collection objects with wrong display of collecting event: only use count instead of locality name

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#3]
In some collection objects that have only asserted distributions the names of province or country are not displayed. Examples:

holotype of _Anisophya punctinervis_ (asserted distribution: Buenos Aires)
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/5ec9dd29-181b-44ef-b5be-1a0e7dc4d965)

syntype of _Anisophya brasilienis_ (asserted distribution: Buenos Aires)
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/2caacbac-5511-4d1b-860b-09b662bbda8b)

syntype of _Hyperophora major_ (asserted distribution: Paraguay)
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/b19175bf-7275-42d0-adc6-05eff506bd78)

The first and the third are OK in the sandcastle, the second has the same problem there.

How can this be fixed? How to find other cases?

**Comment by LocoDelAssembly** [comment]
@jlpereira this comes from DwC index? @mjy no data is generated if coordinates are missing?

**Comment by mjy** [comment]
It is likely drawing from CE cached fields, which in turn are referenced in DwC.  This issue is that not all GeographicAreas have ranks at all three levels that can be determined precisely at those levels.  Essentially GeographicArea type differs across the globe.

**Comment by typophyllum** [comment]
This looks correct now.
