### ISSUE TITLE
 Taxon Pages DwC export complications.

### ISSUE THREAD

**Issue by mabecabrera** [sfg-taxonpages/orthoptera#30]
From my PC at the museum, when I click on the DWC button (https://sfg-taxonpages.github.io/orthoptera/#/otus/930579/overview),  

I get this:

![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/72e08d96-0888-4ba4-86d6-f9d02b492fea)

Do not know how to make it look like organized in columns. Having a hard time here...

**Comment by mabecabrera** [comment]
The same thing happens when downloading in .CSV from the filters results.

**Comment by mabecabrera** [comment]
![image](https://github.com/sfg-taxonpages/orthoptera/assets/63611746/20e2551d-7f3c-468f-a733-4ad0fe311185)

**Comment by debpaul** [comment]
@mabecabrera 
- how are you opening these files? Please try this.

1. Download the file. 
2. Open Excel.
3. Inside Excel, go to the `Data` tab (see screenshot below)
4. In the `Data` tab, find the icon (somewhere on the left, that says `from Text / CSV`)
5. Click that `from Text/CSV` and you will point it to your downloaded file to begin import.
6. This ought to result in data that comes into Excel as you expect.
7. If not, send picture of what you're clicking on inside Excel to open this file ... hope this helps!

![image](https://github.com/sfg-taxonpages/orthoptera/assets/2990155/5fda637d-595f-4939-8b21-2967b4bc60d7)

**Comment by mabecabrera** [comment]
Thank you @debpaul ! It works! I will close it now.
