### ISSUE TITLE
Why is Sphodromerus serapis an invalid taxon?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#31]
https://sfg-taxonpages.github.io/orthoptera/#/otus/934663/overview

Cannot find the reason for invalidity

A map should be available, see Old OSF. Interestingly I found this taxon by geo-searching in the area

**Comment by typophyllum** [comment]
Strange. The correct one is there:
https://sfg-taxonpages.github.io/orthoptera/#/otus/819550/overview
Can't find OTU 934663 with the normal search in TP.

**Comment by mjy** [comment]
> So the geographic search seems to find OTUs that shouldn't be included.

Checking.

**Comment by mjy** [comment]
Can someone give me the rough shape they used in that search via a screenshot?

**Comment by klausriede** [comment]
https://sfg-taxonpages.github.io/orthoptera/#/otus/819550/overview is (now?) a valid taxon. However map could be improved because type is from Sinai, the only area NOT coloured blue in the map
