### ISSUE TITLE
Bactrophorinae occuring in france

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#32]
according to overview map https://sfg-taxonpages.github.io/orthoptera/#/otus/823545/overview

fortunately a precise search around France reveals no invasive OTUs yet.... (Bactrophorinae is neotropical)

**Comment by typophyllum** [comment]
This is a known problem. All taxa occuring in French Guiana are shown to occur also in France and vice versa.

**Comment by typophyllum** [comment]
This seems to be fixed.

**Comment by mjy** [comment]
@typophyllum I think it is indeed handled now.  If you want to discover new issues focus your attention on taxa located in central South America.  We have some updates coming, but it would be good to get confirmation on specifics.
