### ISSUE TITLE
syntype photographs of Lezina concolor missing

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#36]
http://orthoptera.speciesfile.org/Common/basic/ShowImage.aspx?TaxonNameID=1131761&ImageID=133632 not available in sfg...

**Comment by LocoDelAssembly** [comment]
Isn't it the second image?
![image](https://github.com/sfg-taxonpages/orthoptera/assets/4991925/4e4d6103-8452-496f-92cc-059eb9eeb157)

**Comment by typophyllum** [comment]
The images should have migrated without problems. The seven photos in the old OSF are all present (see Hernán's screenshot above).

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/2c4eee2a-d23c-4e4c-9bf7-1c236b9f3f8d)
