### ISSUE TITLE
Type specimens without OTUs

### ISSUE THREAD

**Issue by mjy** [sfg-taxonpages/orthoptera#37]
A common routine check is this query: https://sfg.taxonworks.org/tasks/collection_objects/filter?per=50&type_material=true&taxon_determinations=false&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels&page=1

It shows all type material (linking specimen to names) that aren't assigned to OTUs.  These type material won't be mapped is the primary issue.

**Comment by typophyllum** [comment]
Thanks. These three holotypes were among the very first ones I added after the migration.
