### ISSUE TITLE
TaxonPages lists paralectotype instead of lectotype

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#4]
In the species _Brachytrupes calaharicus_ (above TaxonPages, below TaxonWorks):
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/5cafd0fc-617b-4800-89e0-c175d1000a6b)
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/7a4995aa-8515-4b97-bef3-bbb89248b5d6)

**Comment by jlpereira** [comment]
Done
