### ISSUE TITLE
Searching for Stenopelmatoidea in Central Europe

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#40]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/6f8871e9-bf45-4d5c-9ff9-ee655023ffdc)

shows Stenopelmatodiea occuring in Germany . However if I do a search (generous bounding box in Central Europe) I do not find OTUs
If a region is coloured there must be some data justifying occurence, and I would like to retrieve them...

**Comment by typophyllum** [comment]
Same French Guiana-France bug as in #32 and #33.
