### ISSUE TITLE
OGUs

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#41]
Here is anothern one https://sfg-taxonpages.github.io/orthoptera/#/otus/827024/overview Anchotatus, entering into Europe via Netherland Antilles. I think the solution is simple, please check the Operational Geographic Units! The map is correct if Overseas territories are correctly associated with France, Netherlands respectively . So you get an occurence in netherland antilles, and your OGU Netherlands will show up in the map which is correct! A possible solution would be to use smaller administrative units (which are more stable anyway, particularly in Europe), or use biogeographic realms instead of political boundaries.

**Comment by MMCigliano** [comment]
we are trying to find the solution, Exploring the possibility of using h3 graphs

**Comment by MMCigliano** [comment]
Problem solved
