### ISSUE TITLE
links to sound recordings are broken

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#45]
They don't direct to orthoptera.archive.speciesfile.org and now produce a 404 (page not found) error.

Example:
https://orthoptera.speciesfile.org/Common/basic/PlaySound.aspx?TaxonNameID=1245059&SoundID=3242

Apart from the missing .archive, https apparently needs to be replaced by http.

**Comment by typophyllum** [comment]
The obsolete broadcast message should definitely be removed. If there are species files that did not yet migrate they can use Announcements instead.

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/25daef62-5f80-4873-b2c3-bd9faf6a6e6b)

working link:
http://orthoptera.archive.speciesfile.org/Common/basic/PlaySound.aspx?TaxonNameID=1245059&SoundID=3242

**Comment by typophyllum** [comment]
Is this very complicated to fix? I think this is a very serious error and it looks embarrassing.

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/51c19692-aa6e-4f9a-bee7-98daaccf5fad)

**Comment by LocoDelAssembly** [comment]
Fixed by HTTP 302 non-permanent redirect to archive sites. This applies to all SFs.
