### ISSUE TITLE
invalid values in decimal...columns

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#46]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/e8824ae9-2d96-4454-8117-74e97cbba156)

for Gomphocerippus (which as we know has a wrong map with values in Madagascar, French Guiana).
A DwC download shows these invalid values for decimal degrees. Should be easy to find more by checking validity in columns
https://sfg-taxonpages.github.io/orthoptera/#/otus/812945/overview

**Comment by LocoDelAssembly** [comment]
Is this issue senior synonym of https://github.com/sfg-taxonpages/orthoptera/issues/49?

**Comment by klausriede** [comment]
not sure...needs to be confirmed. Why are some values corrupt and others not? Maybe a CSV download is more reliable? Or a tabular display on the website? Where do I find this object on the map?

**Comment by mjy** [comment]
Duplicate, CSV is always source of "truth".
