### ISSUE TITLE
sounds disappeared completely

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#47]
https://orthoptera.speciesfile.org/Common/basic/PlaySound.aspx?TaxonNameID=1143093&SoundID=1358

**Comment by typophyllum** [comment]
Mentioned three days ago in #45. Hope this serious error will soon be fixed.

**Comment by mjy** [comment]
This is because of http:// vs. https://.

**Comment by klausriede** [comment]
should be easy to resolve!

**Comment by LocoDelAssembly** [comment]
Duplicate of https://github.com/sfg-taxonpages/orthoptera/issues/45 (solved)

**Comment by klausriede** [comment]
yes, great http://orthoptera.archive.speciesfile.org/Common/basic/PlaySound.aspx?TaxonNameID=1105934&SoundID=1233
