### ISSUE TITLE
synonym relationship lost

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#48]
At _Miramella (Kisella) alpina subalpina_ (Fischer, 1850). Harz 1975 was not cited and the relationship was missing (fixed).

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/76089098-5bea-4bfa-bbfc-fb13371cafba)

**Comment by typophyllum** [comment]
This seems to be a frequent problem.  At _Gryllodes greeni_ a recent synonym relationship was assigned to a no-author duplicate and it was under a wrong valid species.

**Comment by typophyllum** [comment]
Frequent problem with synonyms and odd combinations of valid names, still being fixed with fixing no-author duplicates and checking also other synonyms of corresponding valid name.

**Comment by klausriede** [comment]
seems there is something wrong with the new datamodel OR the migration algorithm OR both....
