### ISSUE TITLE
Cycloptilum kelainopum distribution (Grylloidea: Mogoplistidae)

### ISSUE THREAD

**Issue by relbugman** [sfg-taxonpages/orthoptera#56]
The distribution map for Cycloptilum kelainopum Love & Walker 1979 is incorrect and incomplete as per original (and only) publication - no other references are listed except mention of SINA which agrees with L & W.
The distribution map shows a location as High Island, Lake Michigan in Michigan USA.  This, by my experience (and description) is highly improbable, and is not supported by any listed reference. I would be extremely surprised at locations north or inland from the Gulf of Mexico and SE US coastal plains.
Also, the paratype series includes a male from Jefferson County, TX in trees just back of beach.  There are additional records (unpublished photograph in iNaturalist, identified by me) in TX supporting this range.  This is not shown in the distribution map.
Otherwise, I'm learning to use this new resource!  I have several questions re. the assignment of genera to tribes and subtribes, and will be in contact later.

**Comment by relbugman** [comment]
Thanks, Holger.  I'm still keeping up on Mogos and working on Baja Calif.  I was still at Gainesville until 1968 and knew of no MI specimens.  Is the Tom Walker database from 2008 that you cite available anywhere online, or at UF, or from Tom?  I find no mention in my 'old' OSF I still keep available, either mapped or listed source.It's taking some effort to get used to the new version, but looks good!Bob Love.
    On Thursday, November 16, 2023 at 10:03:26 AM EST, Holger Braun ***@***.***> wrote:  
 
 


Thank you. This was based on specimens collected in 1965 and based on Tom Walker's database from February 2008, already in the old OSF. Probably an error or a misidentification. I deleted the specimens and removed the asserted distribition for Michigan. I will add the paratype from Texas after the lunch brake.

Please let us know if you find more questionable data.

**Comment by typophyllum** [comment]
Tom's GrylTett Database seems to be still available at SINA: https://orthsoc.org/sina/h00dbase.htm
Interestingly, the "Michigan" specimens had the exact same collection date as the paratype from Texas, so most likely a locality error.
