### ISSUE TITLE
Jodacris ferruginea ferruginea listed 2 times

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#58]
https://orthoptera.speciesfile.org/otus/822013/overview
ssp listed 2 times, once without pic. Might be a problem if users did not realize the duplication but end up with the version without a pic. So they might think OSF does not have a pic. But it has!

**Comment by typophyllum** [comment]
The link goes to the species, but _Jodacris ferruginea ferruginea_ was indeed duplicated. One with all citations and the the wrong original combination _Anniceris ferruginea_ and another one with only citing the correct protonym _Anniceris ferrugineus_ (_Anniceris_ is treated as masculine by the different authors). Now it's fixed.

Thanks for reporting. Knows the cuckoo how this happened (same in the sandcastle).
