### ISSUE TITLE
https://orthoptera.speciesfile.org/otus/837419/overview Neoscapteriscus 

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#59]
...occuring in Australia? Introduced?How do I find the respective reference? Seems there are no specimens of this neotropical species in the area ....

**Comment by klausriede** [comment]
we should find this reference preferably when clicking on australia ...Interestingly I found that Catalogue of Life manages geographic citations with references showing up when hovering over the country name, however, this citation is missing . Note Author S.F. Group....
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/c1efd5b5-c252-454d-8dc3-c17f0fd5b2d7)

**Comment by typophyllum** [comment]
Of  specimen records (often with source) from the old OSF were created also asserted distributions with this strange source:
https://github.com/sfg-taxonpages/orthoptera/issues/50

In TW the specimens do have the source, in this case Hebard 1924 for Ecuador (Guayas, the coordinates are exaggeratedly precise) and  Rehn 1903 for Nicaragua. From French Guiana is the type.
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/cffcbcb5-60a1-4fd0-a802-38204d7db482)
