### ISSUE TITLE
iNaturalist flag with note on  Hemiandrus superba  https://www.inaturalist.org/flags/603622 may be of interest

### ISSUE THREAD

**Issue by mjy** [sfg-taxonpages/orthoptera#60]
FYI there is a conversation perhaps of interest here: https://www.inaturalist.org/flags/603622.  Might be good to have a curator chime in there.  I let Scott (iNat admin) know of this issue tracker, but would be good to announce it there too.

**Comment by danilohegg** [comment]
See the International Code of Zoological Nomenclature: 
https://www.iczn.org/the-code/the-code-online/

Article 34.2:
The ending of a Latin or latinized adjectival or participial species-group name must agree in gender with the generic name with which it is at any time combined [[Art. 31.2](https://code.iczn.org/formation-and-treatment-of-names/article-31-species-group-names/#art-31-2)]; if the gender ending is incorrect it must be changed accordingly (the author and date of the name remain unchanged [[Art. 50.3.2](https://code.iczn.org/authorship/article-50-authors-of-names-and-nomenclatural-acts/#art-50-3)]).

_Hemiandrus_ is male gender; _Superbus_ is an adj., and needs to take the same gender as the noun it is associated with

**Comment by typophyllum** [comment]
The Latin word is indeed an adjective. Adding this information to TW as well as establishing _Hemiandrus_ to be masculine automatically adapts the name to _Hemiandrus superbus_.
