### ISSUE TITLE
Trigonidium gender and agreement of suffixes

### ISSUE THREAD

**Issue by sjl197** [sfg-taxonpages/orthoptera#61]
It looks like OSF are  perhaps making some errors with the gender formation of several species in Trigonidium. From wider context, i'd anticipate you're treating Trigonidium as neuter.  [Gender is not defined originally, nor from original species T. cicindeloides, and for record I did not do 'due diligance' search the literature]. Well, IF so - then for example a couple in different subgenera such as Trigonidium (Trigonidium) australiana (Chopard, 1925) are arguably wrong gender. But where more noticeable ones are is many of those elsewhere listed under Metioche Stål, 1877 as a valid genus [which seems feminine from its formation, e.g. https://en.wikipedia.org/wiki/Metioche_(cricket)]. But now, OSF has 'Metioche' re-listed as a subgenus of (neuter?) Trigonidium., making Trigonidium (Metioche) Stål, 1877
https://orthoptera.speciesfile.org/otus/834701/overview

If above is correct, then i wonder if a broad selection need updating from what seem feminine to neuter, for example (but not only these few)
Trigonidium (Metioche) apicalis Chopard, 1930 -> apicale
Trigonidium (Metioche) bimaculata (Chopard, 1952) -> bimaculatum
Trigonidium (Metioche) lateralis (Chopard, 1927) -> laterale
Trigonidium (Metioche) ocularis (Saussure, 1899) -> oculare
Trigonidium (Metioche) sexmaculata (Chopard, 1952) -> sexmaculatum
etc

Then see for example confusion within one of the species with two forms presented equally
Trigonidium (Metioche) perpusillum perpusillum Bolívar, 1912
Trigonidium (Metioche) perpusillum perpusilla Bolívar, 1912
The latter with species in neuter and subspecies in feminine.

Regards,
Stuart Longhorn

**Comment by typophyllum** [comment]
_Trigonidium_ seems to be neuter, like al generic names ending in -idium. The name of the type species T. cicindeloides, named after its resemblance to a tiger beetle of the genus _Cicindela_, could perhaps considered to be a noun in apposition. The other species names that are clearly adjectives need to be adapted.

While in the old OSF the species names were edited individually, TaxonWorks adapts the names automatically when the gender of the genus name is established and the part of speech of the species name is selected. Currently this information is incomplete (it wasn't possible to specify this in Species File Software). I will verify the _Trigonidium_ species tomorrow.

**Comment by sjl197** [comment]
Many thanks for response a couple of days ago, and glad that you also saw need that some of these species named being bringing inline. I find it can be tricky to be confident on the gender of some generic names, but  to my eye also that one looked clearly neuter from both its wider historic usage (beyond that said in its original definition with type species named using a noun in apposition) and the likely word origins - as you said above.

I'm on the team of another TaxonWorks- based project (for Harvestmen) so I already understood your core framework could easily support these being brought inline, so thank-you for quickly looking into those, i see that several have been shifted since the messages above. For me, the issue came up casually as a general flag notification on iNaturalist on one of the species, then rather than a quick fix on iNaturalist it seemed like a request to your team here was needed (before then getting iNaturalist etc inline with updates) - so thank-you. Currently, looking back through what i see on your OSF front end, these others still might need the gender fixed to neuter. I appreciate the scale of task however, and you've likely got lots of other updates pending on the OSF project, which is looking great on the new front end - so nicely done!

--
Trigonidium (Balamara) albovittata (Chopard, 1951)
.
Trigonidium (Metioche) boliviana Chopard, 1956
Trigonidium (Metioche) pallidinervis (Chopard, 1928)
Trigonidium (Metioche) quadrimaculata (Chopard, 1952)
Trigonidium (Metioche) sexmaculata (Chopard, 1952)
Trigonidium (Metioche) substriata (Chopard, 1962)
Trigonidium (Metioche) tacitus (Saussure, 1878)
.
Trigonidium (Parametioche) rectinervis (Chopard, 1951)
Trigonidium (Superstes) superbus (Hugel, 2012)
Trigonidium (Trigonidium) australiana (Chopard, 1925)
Trigonidium (Trigonidium) parinervis (Chopard, 1925), plus subspecies

**Comment by typophyllum** [comment]
Thank you very much for the follow-up. We are still dealing with a gazillion migration errors, but I finally verified and updated most of the _Trigonidium_ species, including all the ones you mentioned. Once the names in iNaturalist are updated the API will find them again.

**Comment by sjl197** [comment]
Awesome, nicely done. If you may allow me, whilst then adopting those revisions to get iNat inline, i've just noticed that Trigonidium (Metioche) comorana might also benefit from adaption inline as neuter if -> T. comoranum. Sorry to be a pain and highlight this way! There's also a potential homonym issue with those called "nigripes" but those are beyond my scope. Anyway, those aside, feel free to close this issue about the gender agreement overall, thanks for your action.
