### ISSUE TITLE
remove red broadcast message from old OSF (and other archive species files)

### ISSUE THREAD

**Issue by typophyllum** [sfg-taxonpages/orthoptera#63]
This should finally be removed. It doesn't concern public users, and the curators don't need it. In the links to sound recordings it disrupts the display:

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/d972a518-f7c4-47f6-9d3d-1fbe0a36ba61)

If certain species files still need it, the Broadcast message could be replaced by Announcements.

**Comment by mjy** [comment]
@jrflood can you resolve this?
