### ISSUE TITLE
missing pic

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#65]
the picture for Heteracris herbacea (available in old OSF) http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1113836 is missing!
https://orthoptera.speciesfile.org/otus/929688/overview

**Comment by typophyllum** [comment]
I deleted the duplicate OTU. But this is a general problem I already noticed several times.

**Comment by klausriede** [comment]
@mjy @LocoDelAssembly should not be too difficult to write a query/routine [younameit] to detect duplicate OTUs - in fact individual OTUs should be unique?

**Comment by klausriede** [comment]
so what is Acrida herbacea https://orthoptera.speciesfile.org/otus/818025/overview ?

**Comment by typophyllum** [comment]
_Acrida herbacea_ is a different species (n. sp. in Bolívar 1922) with different type locality.

**Comment by LocoDelAssembly** [comment]
@typophyllum when you deleted the duplicate was it after making sure the OTU did not have any data that the corresponding OTU didn't have?

**Comment by LocoDelAssembly** [comment]
As for detecting duplicates, we have multiple OTUs with same taxon name but they differ in that the duplicates have Otu.name set (which is not a taxon name, is kind of label for OTU). To list the duplicates Filter OTU with option `With Name` set to `With` returns the list, about 4100 OTUs.

**Comment by typophyllum** [comment]
Yes, I made sure that the other OTU didn't have anything that the remaining 820712 doesn't have.

Does this mean that there are 4100 names where the search presents a duplicate and then the pictures might be missing on the taxon page?

**Comment by mjy** [comment]
What TaxonName was the original OTU that you destroyed linked to?  OTUs that are linked to synomous TaxonNames should still have their data appear on the TaxonPages, as they are "coordinate" in our sense. If they don't then there is likely a bug.

**Comment by typophyllum** [comment]
I think it was the same situation like in the sandcastle:
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/fda81ab1-5f95-45dd-b5e0-c02baaaf4f4d)
The OTU with both protonym and current combination has been destroyed. Strangley, on its page it did show the three pictures that were missing in TP.
