### ISSUE TITLE
Why is Hemisaga irregularis not in the species group of its name? 

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#66]
Species Hemisaga irregularis is directly attached to genus, while there is a species group using its species epithet. Wouldn't that suggest that the type species for the superspecies irregularis is not H. irregularis? 

https://orthoptera.speciesfile.org/otus/841552/overview
https://orthoptera.speciesfile.org/otus/841565/overview

**Comment by typophyllum** [comment]
Thank you. I moved it under its corresponding superspecies. This was already wrong in the old OSF.

Rentz 2010 lists only three species explicitly under his Irregularis Group, not including the type species. Possibly the five remaining ungrouped species should be included too, according to: "The majority of _Hemisaga_ species belong to this group" (op. cit.).
