### ISSUE TITLE
Species not listed: Goniaea viridis (Sjöstedt, 1921)

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#67]
Info gathered from https://www.inaturalist.org/observations/138704137: States that the species was described in Sjöstedt (1921) and has been treated by more modern researchers as Genus Novum 83 based on the idea it likely doesn't belong to this genus.

**Comment by typophyllum** [comment]
Thank you. I added it. I'm still working slowly (too much other work) through Sjöstedt's monograph to add missing data (many citations apart from the by now three species).

**Comment by typophyllum** [comment]
Found another species that was missing: _Terpillaria callopus_ Sjöstedt, 1921.
