### ISSUE TITLE
Status of Mendes (2016) within the database

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#68]
Orthopteran species was present on iNaturalist (https://www.inaturalist.org/taxa/1262861-Anapolisia-amazonica) but not on OSF. I was able to track down a citation (https://repositorio.inpa.gov.br/handle/1/12483) which accredits eight new species, resurrection of genus Tropicophyllum, and 4 new genera with new species in each of them. Is this an acceptable source?

**Comment by typophyllum** [comment]
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/2816b6ab-45e0-4f68-b9ab-590a0ea804b0)

Seems to be a doctorate thesis and probably no valid publication in the sense of the Code. And not possible to download. I will contact the author.

**Comment by typophyllum** [comment]
The name seems to be still available on iNaturalist, but the two observations have been reidentified to genus level. Author did not respond.
