### ISSUE TITLE
Stats: where are the 9 invalid species?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#70]
https://orthoptera.speciesfile.org/otus/928913/overview

**Comment by MMCigliano** [comment]
I agree with you, Klaus, in the interpretation of the stats is confussing. However, I think that we really need the stats table.
The problem with the stats table is that the Combinations are being included under invalid names.  So technically they are synonyms in some broad sense, but not the protonym sense, only these should be listed under invalid names.

**Comment by klausriede** [comment]
Agree, in fact I wonder if it might be better to list the combinations: for many species vast amounts of non-taxonomic literature exist with combinatorial names . Would be good to see those  immediately in a list

**Comment by MMCigliano** [comment]
The list of combinantions names with the citations are displayed in the Nomenclature pannel.
