### ISSUE TITLE
Moncheca preciosa

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#71]
seems 
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/387642d2-b2bf-46c8-9dc6-230ec9f8cb7a)
depicted here under Moncheca preciosa is another species....? https://orthoptera.speciesfile.org/otus/843708/overview

**Comment by typophyllum** [comment]
Yes, misidentified. Different species of _Moncheca_ or _Vestria_.
