### ISSUE TITLE
issues with https://orthoptera.speciesfile.org/otus/814443/specimen_records

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#72]
seems holotype/syntype pics and captions got mixed up
cf
http://orthoptera.archive.speciesfile.org/Common/specimen/ShowSpecimen.aspx?SpecimenID=71462

**Comment by typophyllum** [comment]
Thanks. Error in the original OSF. Fixed. In the Overview the pictures list the correct collection object for _Acridium delineolatum_ (bb267847-9baa-44a3-96eb-d891ae10d8f3), the tab for Specimen records seems to take time to update.

Browse OTU:
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/a3b6b6dd-c634-46e6-af7f-9c749cd12617)

**Comment by typophyllum** [comment]
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/d6f5b807-041c-457b-a202-a7c43c640fac)

The pictures are still displayed with the wrong specimen. Apparently the Specimen tab loads the pictures only once and then never updates them.
@jlpereira Shall I submit this at https://github.com/SpeciesFileGroup/taxonpages/issues ?

**Comment by jlpereira** [comment]
Solved using Radial CO to regenerate DwC. @mjy It seems that DwC does not regenerate automatically in some cases

**Comment by mjy** [comment]
> ... It seems that DwC does not regenerate automatically in some cases

This is 100% correct.  It's another think we need routine maintence on now.  We'll prioritize to do bi-weekly rebuilds after we get zeitwerk live.

**Comment by typophyllum** [comment]
Thanks. Based on a species list in a grant report I fixed the pictures of type specimens that have been uploaded in November. About half of the photos were missing on the Specimen records tab.

**Comment by klausriede** [comment]
Zeitwerk sounds great https://www.honeybadger.io/blog/ruby-code-loader-zeitwerk/  - particularly the feature "Detect errors before customers can report them..."
