### ISSUE TITLE
stats - 14 names?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#73]
still do not understand the stats tab - do we really need it ? Seems redundant for me.
In any case it should be correct, why are there 14 names listed for fewer synonyms ?
https://orthoptera.speciesfile.org/otus/828190/overview

**Comment by typophyllum** [comment]
Same as here, it counts all combinations instead of only real synonyms:
https://github.com/sfg-taxonpages/orthoptera/issues/70

I find this useless too, maybe comment there:
https://github.com/SpeciesFileGroup/taxonpages/issues/201

**Comment by typophyllum** [comment]
TaxonPages issue.
