### ISSUE TITLE
wrong country in Lactista stramineus

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#74]
see label: Guyana
or see reference: 
http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1104180
Erichson. 1848. Reisen in den Jahren 1840-1849 British-Guiana 3:582 
therefore syntype from British Guiana. 
PS Lactista stramineus does not appear in dropdown list when you search for Lactista.
PPS: anybody knows if it is not Lactista straminea?

**Comment by klausriede** [comment]
Just saw: probably refers to syntypes from Colombia, which are georeferenced! There fore the point. It should be possible to georeference the Erichson Guiana type, do we have a wishlist, project list?

**Comment by typophyllum** [comment]
The country is correct, the syntypes are from Guyana (formerly British Guiana), without any place specifics, so impossible to georeference.

Latin _stramineus_ (straw-colored) is an adjective (original combination _Oedipoda straminea_). But _Lactista_ could me masculine, according to the originally included species names: _L. gibbosus_ and _L.  punctatus_.

**Comment by klausriede** [comment]
Thanks, meanwhile found the Laktistes = greek: Kicker origin in Rowell 2013, p 296. Will try to find better georeferences in https://ia802700.us.archive.org/35/items/reiseninbritisch03scho/reiseninbritisch03scho.pdf
