### ISSUE TITLE
Tettix ignobilis scrutiny not visible

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#77]
https://orthoptera.speciesfile.org/otus/927161/overview
: Tettix ignobilis scrutiny for synonym not visible , see 
http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1234070

**Comment by typophyllum** [comment]
The problem is that the synonyms currently do not have their own pages.

**Comment by klausriede** [comment]
same with http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1108408 which should appear under X. humilis brachycerus, according to the latest publication?
