### ISSUE TITLE
live specimen photograph without date and locality

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#79]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/e980c553-ddf4-4c89-9cea-8130f5503515)

this nice photograph of https://orthoptera.speciesfile.org/otus/816254/overview Baeacris punctulata does not inform about locality and date.

**Comment by MMCigliano** [comment]
Hi Klaus, added the information. 
thank you for pointing out this missing data

**Comment by klausriede** [comment]
denada ... wonder where this specimen appears on the map. It is difficult to relate the collection number objects in the map with the pictures...

**Comment by MMCigliano** [comment]
the information on the collection object is displayed when you click on it, in the Distribution map of Browse OTU
![Uploading image.png…]()

**Comment by klausriede** [comment]
somehow could not see the image you uploaded.
Here what I see when I click to a point in the map:
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/4709821a-1400-4f4f-b00e-f5ea3e9b36ac)

But I do not see the collection date . So hhow do I find this photograph on the map?
And vice versa?

**Comment by klausriede** [comment]
same here:
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/f593b99c-1110-45b0-956e-d70cdefb2ef3)
 Rather than the collection objet number we would like to see the coordinates and the collection data.

**Comment by typophyllum** [comment]
These are shown at the Specimens records:

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/33098a1d-5aa4-4e54-9f1a-678da139d019)
