### ISSUE TITLE
Brachystola magna images lost

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#8]
...seem to be lost in the new version (cf with beautiful images in old OSF 
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/d5126076-8b2f-49a3-8aac-e19c6d5bcbf4)

**Comment by LocoDelAssembly** [comment]
https://sfg-taxonpages.github.io/orthoptera/#/otus/823283/overview

![image](https://github.com/sfg-taxonpages/orthoptera/assets/4991925/d87ca480-462f-4f9c-ae22-6b272251bc35)

However there is a phantom `Brachystola magna` that doesn't have images: https://sfg-taxonpages.github.io/orthoptera/#/otus/927245/overview

![image](https://github.com/sfg-taxonpages/orthoptera/assets/4991925/59a3beac-a054-4ee2-9968-967d6b24901d)

Didn't we have autocompletes set to *NOT* search OTUs with non-nil names ("unlabelled") @jlpereira @mjy?

**Comment by mjy** [comment]
@LocoDelAssembly autocompletes still a mess, still working on them.

**Comment by klausriede** [comment]
eliminate phantoms!

**Comment by typophyllum** [comment]
Where does this phantom come from? The combination (protonym is _Brachypeplus magnus_) doesn't have an OTU.

**Comment by klausriede** [comment]
more about Phantoms: https://wildlabs.net/event/webinar-phantom-orthoptera
