### ISSUE TITLE
why no pictures of Acrotylus insubricus in the overview?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#81]
https://orthoptera.speciesfile.org/otus/810739/overview -many pictures available!

**Comment by klausriede** [comment]
I see . seems the female neotype is missing http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?ExpandImages=1
but no, it appears below, under specimen. Should be under types . Schmiddt misspelled

**Comment by typophyllum** [comment]
I corrected Schmidt's name at the male neotype:
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/ec301883-50c2-42da-8e76-77e2311e0dce)

The neoallotype appears below under normal specimens, since Taxonworks doesn't recognize allotypes.

**Comment by klausriede** [comment]
@LocoDelAssembly  How could you train Taxonworks to "recognize" any types? I think this is a question of database design, in any case any type is not a normal specimen.

**Comment by mjy** [comment]
We explicitly only cover governed types in the semantics of our TypeMaterial model.  Adding logic to the other 80+ is beyond our scope.  To add other types of types you can extend a project with Tags or Data attributes.

**Comment by mjy** [comment]
> governed types?

I should have said governed type types.  I.e. the type types that have nomenclatural consequences  (Holotype, Paratype, etc.).  The specimen classified as an "genotype", "typotype", or "homeotype" for example, has no special nomenclatural bearing.  There are no rules about these type types in the ICZN.

**Comment by klausriede** [comment]
ok, name bearing times. Now this is the opposite case: a (neo)type assigned posthoc isntit? So in this case we should know who did this, when and eventually why. As far as I understand there must not be a publication associated to such an act.

**Comment by klausriede** [comment]
PS it appears under neosyntype in old OSF http://orthoptera.archive.speciesfile.org/Common/specimen/ShowSpecimen.aspx?SpecimenID=83709
