### ISSUE TITLE
Letana atomifera Type

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#83]
I found a Letana atomifera holotype here http://sesam.senckenberg.de/page/index.asp?objekt_id=794321&sprache_kurz=en

It would be interesting to crosscheck these data all DORSA specimens are photographed

**Comment by typophyllum** [comment]
In this case there seems to be a mistake. _Letana atomifera_ (Brunner von Wattenwyl, 1878), described as _Pyrrhicia atomifera_, is based on at least two syntypes from India, which should be in Vienna.
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/a737602a-6fbe-4f07-b77e-e862775f60a5)


Sigfrid Ingrisch's specimen from Nepal is not a type, but should perhaps be added to OSF. It's in alcohol and perhaps not photographed.

**Comment by klausriede** [comment]
I will ask sigfrid about this and the other SESAM data....seems nobody is working in Senckenberg with Sesam and Orthoptera anymore...
