### ISSUE TITLE
How can a neotropical species be a synonym of an African sp?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#85]
https://orthoptera.speciesfile.org/otus/929665/overview

vs
https://gdz.sub.uni-goettingen.de/id/PPN61613617X?tify=%7B%22pages%22%3A%5B102%2C103%5D%2C%22pan%22%3A%7B%22x%22%3A0.518%2C%22y%22%3A0.864%7D%2C%22view%22%3A%22info%22%2C%22zoom%22%3A1.099%7D

(not a database issue, rather a taxonomic question

**Comment by klausriede** [comment]
solution found: the source cites indeed locality Saint Domingue but maybe there is a Saint Domingue in Africa? In any case you find the necessary details in Old OSF http://orthoptera.archive.speciesfile.org/Common/specimen/ShowSpecimen.aspx?Router=NewPage I think we need this info in new OSF

**Comment by typophyllum** [comment]
I can't find any reference to Africa, unless you refer to the work of Palisot de Beauvois 1807: Insectes recueillis en Afrique et en Amérique .......... where _Truxalis notochlorus_ is described. Links to the old OSF without an ID are useless.

Anyway, I removed the misidentified specimen from the south of Brazil, so it was good to bring this up.
