### ISSUE TITLE
tungurahua or Napo

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#86]
https://orthoptera.speciesfile.org/otus/803994/specimen_records

tungurahua appears in the locality of this specimen, I think it is Prov Napo? either or..

**Comment by typophyllum** [comment]
The original data are correct, Misahuallí is in Napo, about 50 km away from Tungurahua Province. The error is produced by TaxonWorks that misinterprets the coordinates.

**Comment by mjy** [comment]
I *think* you can select the correct province if it is available and use the "prioritize geographic area" check (on the CE) to resolve this?

**Comment by typophyllum** [comment]
Thanks. This removed Tungurahua. Napo keeps appearing from the verbatim data.

**Comment by klausriede** [comment]
with exact coordinates it would be possible to make an intersection with available GIS Admin shapes and compare results for the entire OSF specimen data
