### ISSUE TITLE
Pterolepis grallata still treated as Rhacocleis

### ISSUE THREAD

**Issue by matpelissie** [sfg-taxonpages/orthoptera#87]
I was wondering if there was a particular reason for keeping _Rhacocleis grallata_ (Pantel, 1886) within the genus _Rhacocleis_ while all other iberian _Rhacocleis_ species have been moved back to the _Pterolepis_ genus based on the solid revision of [Barranco & Gutiérrez-Rodríguez (2010)](http://graellsia.revistas.csic.es/index.php/graellsia/article/viewFile/176/180)?

Thank you for all this work!
Mathieu

**Comment by typophyllum** [comment]
Thanks for reporting this. I just corrected it. This was a migration error (it is the type species of _Scirtobaenus_ which has a single old synonym relationship citation referring it to _Rhacocleis_ - will add one to Barranco & Gutiérrez-Rodríguez 2010  that treats it as synonym of _Pterolepis_).

**Comment by typophyllum** [comment]
There is an error in the old OSF. It wasn't Burr 1907 but Uvarov 1934 who synonymized _Scirtobaenus_ with _Rhacocleis_. Citations for that name now (currently not displayed separate from _Pterolepis_ in the new public version of OSF):

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/b84bdfde-5891-420b-9206-7c5dceb9acb3)

**Comment by matpelissie** [comment]
Thank you for having identified the origin of the problem and for having fixed it!
