### ISSUE TITLE
M. musicum

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#88]
https://orthoptera.speciesfile.org/otus/926812/overview recordings missing!

**Comment by typophyllum** [comment]
Thanks for reporting this. The species had altogether four OTUs. I deleted three of them, and now the sound links are displayed.

**Comment by klausriede** [comment]
just a question to deepen my understanding: If there are four Operational Taxonomic Units, there are 4 "operators" or operation? Finally, an OTU has been defined/designed by somebody. 4 OTUs might be 4 morphospecies of 16 specimens, 4 of each representing one morphospecies, correct?

**Comment by mjy** [comment]
OTUs in TW are a very loose "uniit of work".  We can imagine the two scenarious you list as possible.  Thinking of 4 operations as the origin of the OTUs is also reasonable.  The 4 may be temporary outcomes of a import process, for example, where certainty of a specific goal is uncertain.  For example in the SFG when names were not completely aligned we took a concervative approach and used an _operation_ to create 4, reather than assume they might be one.  OTUs give us a gateway to more resolution than names alone provide. Whether that resolution is the goal of a project is up to the project's curators.

**Comment by klausriede** [comment]
thanks, so basically I got this right! Now back to the example above: where do the 4 OTUs come from?

**Comment by mjy** [comment]
Almost certainly the process of the import.  More than likely via combinations of data in the original SF that did/not include authors, referenced distributions with name strings that couldn't be matched, etc.  You'd have to do some sleuthing.

**Comment by klausriede** [comment]
suggestion make  a list of Original SF data without authors, name strings without matches etc. Sleuthing these days should be done by AI...
