### ISSUE TITLE
Where is Thetella tarnis?

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#91]
...as described in Otte & Alexander p 194...

**Comment by typophyllum** [comment]
Moved by Gorochov. 1986 to genus _Burcus_ (search with original combination redirects to current):
https://orthoptera.speciesfile.org/otus/833907/overview

**Comment by klausriede** [comment]
yes, I found it shortly later, and deleted this issue, but evidently it was still there...sorry
