### ISSUE TITLE
Ornebius denticauda nomen dubium

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#93]
page (for Otte and Alexander) and hint to nomen dubium is missing in https://orthoptera.speciesfile.org/otus/837117/overview

**Comment by typophyllum** [comment]
Was already there:
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/01495984-7429-4b57-bf96-4dbd488b4d5e)

I added an additional citation to Otte & Alexander for the nomen nudum status.
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/73b20f2a-0b73-450f-ac50-bd8e6295b8c1)
