### ISSUE TITLE
The database is missing three species. 

### ISSUE THREAD

**Issue by SuJie-hbu** [sfg-taxonpages/orthoptera#94]
Dear manager，the database is missing three species of _Larnaca_. I provided a article search (Su, J., Duan, Y. H., Li, Y. H. & Shi, F. M. 2024. Description of three new species of Larnaca Walker, 1869 (Orthoptera: Gryllacrididae: Gryllacridinae) from Xizang, China [J]. Zootaxa, 5453(1): 105–112.)

**Comment by typophyllum** [comment]
Thank you very much for the notification. The three species are now present in OSF.
