### ISSUE TITLE
Complex for Tetrix bipunctata

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#99]
See https://www.inaturalist.org/flags/657018 for discussion

Also a citation using this complex: https://zookeys.pensoft.net/article/68316/

**Comment by MMCigliano** [comment]
We followed Moser et al. (2021), the most recent study on the Tetrix bipunctata complex   https://zookeys.pensoft.net/article/68316/, where the authors recommend that bipunctata and kraussi are considered as separate units until the species question can be answered more precisely.

**Comment by SeanCozart** [comment]
@MMCigliano To clarify my request; what I would like to see implemented into OSF is the complex T. bipunctata. So I guess that will show up in the database as "Tetrix supersp. bipunctata" with T. bipunctata and kraussi as children taxa. iNaturalist uses the term "complex" instead of "superspecies".

**Comment by MMCigliano** [comment]
@SeanCozart , it is done. Thank you for your comments

**Comment by klausriede** [comment]
if we go directly to T. kraussi (for example somebody reading about this species in the literature) https://orthoptera.speciesfile.org/otus/809180/overview it is not clear from this other end  that it is "part" of a complex, it would be good to have this info on the T kraussi Taxonpage

**Comment by klausriede** [comment]
PS: old OSF notges: Moser, H. Baur, A.W. Lehmann & G.U.C. Lehmann. 2021. ZooKeys 1043:33-59  zookeys.pensoft.net >> Note: unclear whether young species or infraspecific ecomorph of T. bipunctata >> Tetrix kraussi - it would be helpful to see these notes in TP

**Comment by MMCigliano** [comment]
Klaus,  you can see the citations' notes under Browse Nomenclature in TW
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=916728

**Comment by klausriede** [comment]
but I think it is important to inform outsiders accessing TP! TPs are OSFs window into the world, and non taxonomists will not  login into TW

**Comment by klausriede** [comment]
If  T. bipunctata and kraussi as children taxa of a super or whatever species this should somehow showup in the T kraussi page..
